---
# production config
version: "3.4"

services:
  redis:
    extends:
      file: docker-compose.common.yml
      service: volatile_redis

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: web3_proxy
      MYSQL_DATABASE: web3_proxy
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - ./data/prod_mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - mode: host
        protocol: tcp
        published: 8307
        target: 8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  arbitrum:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-arbitrum.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7700
        target: 8544

  # avalanche-c:
  #   extends:
  #     file: docker-compose.common.yml
  #     service: web3-proxy
  #   volumes:
  #     - ./config/production-avalanche-c.toml:/config.toml
  #   ports:
  #    - mode: host
  #      protocol: tcp
  #      published: 7701
  #      target: 8544

  bsc:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-bsc.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7702
        target: 8544

  eth:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    command: --config /config.toml --workers 48
    volumes:
      - ./config/production-eth.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7703
        target: 8544

  fantom:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-fantom.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7704
        target: 8544

  gnosis:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-gnosis.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7705
        target: 8544

  goerli:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-goerli.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7706
        target: 8544

  optimism:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-optimism.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7707
        target: 8544

  polygon:
    extends:
      file: docker-compose.common.yml
      service: web3-proxy
    volumes:
      - ./config/production-polygon.toml:/config.toml
    ports:
      - mode: host
        protocol: tcp
        published: 7708
        target: 8544
