[package]
name = "entities"
version = "0.3.0"
edition = "2021"

[lib]
name = "entities"
path = "src/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.9.3"
serde = "1.0.145"
uuid = "1.1.2"
