[package]
name = "entities"
version = "0.28.0"
edition = "2021"

[lib]
name = "entities"
path = "src/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.11.3"
serde = "1.0.163"
uuid = "1.3.3"
ethers = "2.0.4"
ulid = "1.0.0"
